# -*- coding: utf-8 -*-
"""01-Series.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LzQBrLwc-gGCuWzjPf4mAUO0hOXiSSuJ

# Introduction to Pandas

![alt text](http://i1.wp.com/blog.adeel.io/wp-content/uploads/2016/11/pandas1.png?zoom=1.25&fit=818%2C163)

Pandas is an open-source, BSD-licensed Python library providing high-performance, easy-to-use data structures and data analysis tools for the Python programming language. You can think of pandas as an extremely powerful version of Excel, with a lot more features.

## **About iPython Notebooks**

iPython Notebooks are interactive coding environments embedded in a webpage. You will be using iPython notebooks in this class. You only need to write code between the ### START CODE HERE ### and ### END CODE HERE ### comments. After writing your code, you can run the cell by either pressing "SHIFT"+"ENTER" or by clicking on "Run Cell" (denoted by a play symbol) in the left bar of the cell.

**In this notebook you will learn -**

* Series
* DataFrames
* Missing Data
* GroupBy
* Merging, Joining and Concatenating
* Operations
* Data Input and Output

## Importing Pandas
To import Pandas under the name **pd** write the following:
"""

import numpy as np
import pandas as pd

"""#Series

The first main data type we will learn about for pandas is the Series data type. 

Series is a one-dimensional labeled array capable of holding any data type (integers, strings, floating point numbers, Python objects, etc.). The axis labels are collectively referred to as the index.

A Series is very similar to a NumPy array (in fact it is built on top of the NumPy array object). What differentiates the NumPy array from a Series, is that a Series can have axis labels, meaning it can be indexed by a label, instead of just a number location. It also doesn't need to hold numeric data, it can hold any arbitrary Python Object.

The basic method to create a Series is to call:

s = pd.Series(data, index=index)

### Creating a Series

You can convert a list,numpy array, or dictionary to a Series:
"""

labels = ['a','b','c']
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {'a':10,'b':10,'c':30}

"""** Using Lists**"""

pd.Series(data=my_list)

pd.Series(data=my_list,index=labels)

pd.Series(my_list,index=['x','y','z'])

s = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])
s

"""** NumPy Arrays **

If data is an ndarray, index must be the same length as data. If no index is passed, one will be created having values [0, ..., len(data) - 1].
"""

pd.Series(arr)

pd.Series(arr,labels)

"""** Dictionary**"""

pd.Series(d)

"""**From scalar value**

If data is a scalar value, an index must be provided. The value will be repeated to match the length of index
"""

pd.Series(3., index=['a', 'b', 'c', 'd', 'e'])

"""**Exercise 1.1:**

Create a Pandas series from Numpy array **arr** of odd numbers between 40 to 50.
"""

### START CODE HERE ### 


### END CODE HERE ###

"""**Expected Output:**

0    41

1    43

2    45

3    47

4    49

dtype: int64

### Data in a Series

Like a NumPy array, a pandas Series has a dtype.

s.dtype

A pandas Series can hold a variety of object types:
"""

pd.Series(data=labels)

# Even functions (although unlikely that you will use this)
pd.Series([sum,print,len])

"""## Using an Index

The key to using a Series is understanding its index. Pandas makes use of these index names or numbers by allowing for fast look ups of information (works like a hash table or dictionary).

Let's see some examples of how to grab information from a Series. Let us create two sereis, ser1 and ser2:
"""

ser1 = pd.Series([1,2,3,4],index = ['USA', 'Germany','USSR', 'Japan'])

ser1

ser2 = pd.Series([1,2,5,4],index = ['USA', 'Germany','Italy', 'Japan'])

ser2

ser1['USA']

"""Operations are then also done based off of index:"""

ser1 + ser2

"""**Exercise 1.2**

Create another pandas series **arr2** of even numbers from 20 to 30 using numpy and add this newly created series with **arr** in the previous exercise.
"""

### START CODE HERE ### 


### END CODE HERE ###

"""Let's stop here for now and move on to DataFrames, which will expand on the concept of Series!
# Great Job!
"""